name: Update GitHub profile

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 1.7.1

      - name: Install dependencies
        run: poetry install

      - name: Update GitHub profile
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: poetry run python src/main.py --live

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: README.adoc
          default_author: 'github_actions'
          message: '[skip ci] Update GitHub profile'
